name: lmtools
channels:
  - conda-forge
dependencies:
  - gdal
  - libspatialindex
  - rtree
  - sphinx-autoapi
  - numpy
  - defusedxml
  - coverage
  - coveralls
  - pytest
  - pytest-cov
  - requests
  - matplotlib
  - openjdk=8
  - pip=21.3.1
  - pip:
    - sphinx-rtd-theme
    - dendropy
    - specify-lmpy
